from random import *

'''This module is a user defined module.
It has various words from the home-row, top-row and other parts.
It is meant to aid typing programs'''

#home, top, homebottom, tophome, topbottom, engwords, 

home_row = ['aa', ' ad', ' ag', ' ah', ' al', ' as', ' fa', ' ha', ' ka', ' la', ' sh', ' aah', ' aal', ' aas', ' add', ' ads', ' aff', ' aga', ' aha', ' ala', ' all', ' als', ' ash', ' ask', ' ass', ' dad', ' dag', ' dah', ' dak', ' dal', ' fad', ' fag', ' fas', ' gad', ' gag', ' gal', ' gas', ' had', ' hag', ' hah', ' haj', ' has', ' jag', ' kaf', ' kas', ' lad', ' lag', ' las', ' sad', ' sag', ' sal', ' sha', ' shh', ' ska', ' aahs', ' aals', ' adds', ' agas', ' agha', ' alas', ' alfa', ' alga', ' alls', ' asks', ' dada', ' dads', ' daff', ' dags', ' dahl', ' dahs', ' daks', ' dals', ' dash', ' dhak', ' dhal', ' fads', ' fags', ' fall', ' fash', ' flag', ' flak', ' gads', ' gaff', ' gaga', ' gags', ' gala', ' gall', ' gals', ' gash', ' glad', ' haaf', ' hadj', ' hags', ' haha', ' hahs', ' hajj', ' half', ' hall', ' hash', ' jagg', ' jags', ' kaas', ' kafs', ' kaka', ' khaf', ' lads', ' lags', ' lakh', ' lall', ' lash', ' lass', ' saga', ' sags', ' sall', ' sals', ' sash', ' sass', ' shad', ' shag', ' shah', ' skag', ' skas', ' slag', ' aghas', ' alfas', ' algal', ' algas', ' dadas', ' daffs', ' dagga', ' dahls', ' dhaks', ' dhals', ' falls', ' flags', ' flash', ' flask', ' gaffs', ' galah', ' galas', ' galls', ' glads', ' glass', ' haafs', ' hadal', ' hahas', ' halls', ' jaggs', ' kakas', ' kasha', ' khafs', ' lakhs', ' lalls', ' sagas', ' salad', ' salal', ' salsa', ' shads', ' shags', ' shahs', ' shall', ' skags', ' skald', ' slags', ' slash', ' alaska', ' daggas', ' fallal', ' flasks', ' galahs', ' halala', ' hallah', ' kashas', ' salads', ' salals', ' salsas', ' skalds', ' alaskas', ' alfalfa', ' ashfall', ' fallals', ' haggada', ' halakah', ' halakha', ' halalah', ' halalas', ' hallahs', ' alfalfas', ' ashfalls', ' haggadah', ' haggadas', ' halakahs', ' halakhas', ' halalahs', 'haggadahs']

top_row= ['piroque', 'poutier', 'wipeout', 'equipt', 'equity', 'piquet', 'poetry', 'pouter', 'purity', 'pyrite', 'quoter', 'qwerty', 'roquet', 'torque', 'towery', 'troupe', 'typier', 'uptore', 'equip', 'erupt', 'outer', 'outre', 'pewit', 'piety', 'pique', 'pouty', 'power', 'purty', 'query', 'quiet', 'quire', 'quirt', 'quite', 'quoit', 'quote', 'repot', 'ropey', 'roque', 'route', 'tepoy', 'toper', 'toque', 'tower', 'towie', 'tripe', 'trope', 'twerp', 'twirp', 'twyer', 'uteri', 'wiper', 'write', 'wrote', 'etui', 'euro', 'peri', 'pert', 'pierpity', 'poet', 'pore', 'port', 'pour', 'pout', 'prey', 'prow', 'pure', 'puri', 'pyre', 'pyro', 'quip', 'quit', 'repo', 'riot', 'ripe', 'rite', 'rope', 'ropy', 'rote', 'roti', 'roup', 'rout', 'ryot', 'tier', 'tire', 'tiro', 'tope', 'tore', 'tori', 'tory', 'tour', 'towy', 'trey', 'trio', 'trip', 'trop', 'trow', 'troy', 'true', 'type', 'typo', 'tyre', 'tyro', 'weir', 'wept', 'wert', 'wipe', 'wire', 'wiry', 'wore', 'wort', 'writ', 'yeti', 'yore', 'your', 'yurt', 'ire', 'opt', 'ore', 'ort', 'our', 'out', 'owe', 'per', 'pet', 'pew', 'pie', 'pit', 'poi', 'pot', 'pow', 'pro', 'pry', 'pur', 'put', 'rep', 'ret', 'rip', 'roe', 'rot', 'row', 'rue', 'rut', 'rye', 'tie', 'tip', 'toe', 'top', 'tor', 'tow', 'toy', 'try', 'two', 'ute', 'wet', 'wit', 'woe', 'wot', 'wry', 'wye', 'yep', 'yet', 'yew', 'yip', 'you', 'yow', 'yup']

home_bottom_row = ['schmalz','bhangs','blacks','changs','flanks',
'clanks','glands','blanch','blanks','clangs',
'flacks','chalks','vangs','flans','fangs',
'ankhs','flack','snack','machs','flash',
'shack','black','skald','hacks','clank',
'bands','clang','hands','calfs','clans',
'lands','clams','khans','slang','blank',
'bhang','gnash','chads','scald','balms',
'clads','jambs','blams','flabs','schav',
'slank','clags','sangh','bangs','dahls',
'glads','chang','dangs','khafs','calks',
'chams','bland','lakhs','hangs','balks',
'blahs','gambs','shank','dhals','balds',
'flams','slack','gland','chalk','halms',
'chasm','lacks','lambs','jacks','calms',
'backs','flank','clash','hanks','damns',
'smack','dhaks','flags','glans','flask',
'banks','macks','nags','skag','jabs',
'lacs','hack','lakh','fads','dhak',
'snag','lamb','gals','gams','bans',
'band','bang','gamb','lads','halm',
'bank','clan','falx','clam','clag',
'clad','lank','hams','alms','gabs',
'sank','gads','gash','back','bach',
'lams','ands','glad','cabs','macs',
'dahl','kafs','sang','sand','mags',
'fans','dags','mads','lack','dabs',
'hadj','khan','dahs','flan','bask',
'bash','labs','mans','jams','jamb',
'dams','cads','dals','sack','dhal',
'bams','calx','khaf','lags','fash',
'calk','damn','calm','mach','calf',
'vans','flax','scad','slag','flag',
'vang','flab','flam','jags','flak',
'kvas','mack','cash','cask','slam',
'dank','dang','scam','chad','scan',
'vacs','half','scab','scag','cham',
'dash','blah','blam','cans','albs',
'slab','bags','daks','kabs','shag',
'shad','lavs','lash','sham','hank',
'balm','balk','ankh','bald','hang',
'hand','bals','nabs','lang','land',
'bads','fang','cams','zags','mask',
'mash','hags','jack','alb','ska',
'fas','als','haj','ads','kab',
'adz','jam','fad','jag','has',
'dag','dal','dah','dak','fan',
'bas','sab','bag','bad','man',
'ban','bal','bam','bah','lad',
'sad','abs','lag','gam','ask',
'ash','ham','lax','zag','dab',
'mas','zax','van','sha','vac',
'las','sal','vas','sag','gas',
'gan','gal','fax','gab','had',
'lac','jab','can','cam','cab',
'cad','and','gad','sac','sax',
'nah','nam','lam','dam','hag',
'nab','kaf','max','lab','kas',
'mac','mad','mag','lav','nag',
'hm','ah','ha','ba','la',
'ka','ag','an','ma','ab',
'ad','am','al','as','ax',
'na','fa','sh']




top_bottom_row = ['procumbent','centumvir','convexity','ectropium','embryonic',
'embryotic','emunctory','entropium','eurytopic','importune',
'impotency','microtube','prozymite','puromycin','pyroxenic',
'querimony','biconvex','biometry','bouncier','bronzite',
'brunizem','cenobium','combiner','comprint','computer',
'contrive','coquetry','coturnix','emictory','enormity',
'entropic','eponymic','eruption','eutropic','inceptor',
'incumber','intercom','neurotic','orpiment','outprice',
'oximetry','pentomic','pivotmen','pretonic','province',
'proxemic','pubowner','punitory','quixotry','requinto',
'ribozyme','timeworn','tubeworm','unerotic','unexotic',
'unpoetic','uptowner','viewport','benzoic','bevomit',
'bicorne','biotype','bitumen','bornite','bouncer',
'bouvier','brevity','briquet','bromine','bromize',
'brownie','brucine','brucite','bumpier','buntier',
'butyric','butyrin','buxomer','bynempt','bywoner',
'centimo','centrum','century','coenuri','cointer',
'combine','comique','compter','compute','conquer',
'convert','corneum','cornute','corvine','counter',
'country','couvert','coverup','cowrite','croquet',
'crownet','crumpet','cumbent','cuprite','curvity',
'cutover','cutworm','cyprine','embrown','embryo',
'emotion','encrypt','enquiry','entomic','entopic',
'entropy','enzymic','equinox','eutropy','evictor',
'exciton','excitor','expunct','extropy','iceworm',
'imbower','imbrown','imbrute','impower','improve',
'imputer','incomer','incurve','meropic','metopic',
'mezquit','microbe','minceur','minuter','mixture',
'monture','mortice','mounter','mowburn','muntrie',
'myotube','nepotic','noticer','nourice','nowtier',
'numeric','omneity','omniety','oriency','overbuy',
'overcut','overmix','overtip','oxyntic','pericon',
'picquet','picture','pimento','pinetum','pinworm',
'piroque','pivoter','pointer','poncier','porcine',
'portmen','potency','pouncer','pouncet','poutier',
'poutine','poverty','premixt','princox','probity',
'promine','protein','protium','provine','proxime',
'pterion','pteroic','puberty','pumicer','purview',
'pycnite','pyretic','pyrexic','pyruvic','quivery',
'quixote','quoiter','recount','rection','remount',
'rentboy','repoint','repunit','rocquet','routine',
'rubicon','ruction','runtime','terbium','timbery',
'tobymen','tonemic','torquey','tourney','touzier',
'townier','towzier','toxemic','tribune','trionym',
'tripmen','trizone','tropine','trounce','tumpier',
'turbine','turnipy','tyronic','umbonic','umptier',
'uncover','unibrow','unmiter','unmitre','unrivet',
'unvoice','unwrite','unwrote','upborne','venturi',
'verminy','viceroy','vicomte','victory','vitreum',
'voiture','vomiter','wintery','wipeout','wombier',
'writeup','xerotic','zoecium','zymotic','bemixt',
'bepity','betony','betrim','beworm','bicorn',
'bicron','bitzer','bizone','bonier','bonxie',
'bonzer','bounce','bouncy','bounty','bourne',
'bovine','bowery','bowmen','bowtie','bowyer',
'boxier','breton','briony','bromic','bromin',
'bronze','bronzy','brouze','browny','brucin',
'brunet','bumper','bunter','bunyip','burnet',
'burnie','burton','byrnie','centry','centum',
'cerium','cervix','cinque','cirque','citron',
'cobnut','coempt','coiner','comber','comity',
'comper','conium','conure','convex','convey',
'copier','copter','coquet','corbie','corium',
'cornet','cortex','cortin','corvet','corymb',
'cotype','county','couper','courie','couter',
'couzin','covent','covert','covine','covyne',
'cowier','cowmen','cowpie','cowrie','coxier',
'cozier','crepon','cretin','crimen','crimpy',
'crinum','cronet','croupe','croupy','croute',
'cruive','crumby','crumen','crumpy','cruzie',
'crypto','cuiter','cumber','cupmen','curiet',
'curite','curney','curvet','curvey','econut',
'ectopy','embryo','emptor','enmity','entomb',
'enviro','enwomb','eponym','equipt','equity',
'erbium','erotic','eruvim','eruvin','etymic',
'etymon','etypic','exonic','exonym','exotic',
'expiry','export','extirp','icebox','imbrex',
'imbrue','impone','import','improv','impure',
'impute','incept','income','inpour','intomb',
'invert','inwove','iterum','mentor','merino',
'meruit','metric','mevrou','micron','mincer',
'minter','minuet','minute','moiety','montre',
'mopery','mopier','morine','motier','motive',
'mouter','munite','munter','muonic','murein',
'murine','mutine','mutiny','myopic','myotic',
'neumic','nicety','nipter','nitery','nitrox',
'noetic','norite','notice','novice','novity',
'number','numpty','obiter','obvert','optime',
'orbity','orcein','orcine','orexin','orient',
'orpine','ourebi','outbye','outcry','outvie',
'outwin','ouvert','overby','owerby','pectin',
'peinct','penury','permit','pernio','peroxy',
'picote','piment','pincer','pinery','pinout',
'pioner','pioney','piquet','pitmen','poetic',
'poetry','pointe','pointy','poncey','pontic',
'pontie','potmen','potzer','pounce','pourie',
'pouter','powney','pownie','powter','poxier',
'prebuy','precut','premix','prewyn','pricey',
'prince','privet','probie','probit','proine',
'protei','proven','proyne','pruine','pruney',
'pterin','pumice','puncto','punier','punter',
'purine','purity','purvey','pyemic','pyoner',
'pyrite','pyrone','qubyte','queint','quince',
'quinte','quinze','quiver','quoter','qwerty',
'recoin','recomb','recopy','recoup','rectum',
'remint','remixt','renvoi','renvoy','requin',
'requit','retcon','roquet','rounce','rouncy',
'roupet','roupit','rubine','rumpot','tenour',
'terbic','tercio','timber','timbre','tombic',
'tonier','topmen','torque','toupie','tourie',
'towery','towier','townie','toxine','toymen',
'tricep','tripey','triune','trompe','tropic',
'tropin','troupe','trouve','tunier','turion',
'turnip','twerpy','twicer','twiner','twirpy',
'twonie','typier','uberty','ubiety','umbery',
'umpire','unbore','uncoer','uncope','unicom',
'uniter','unmiry','unmixt','unripe','unrobe',
'unrope','unrove','untomb','untrim','unvext',
'unwept','unwire','unwive','unwove','upbore',
'upcome','uptime','uptore','uptorn','uptown',
'upvote','upwent','uremic','uretic','uronic',
'utopic','vector','verity','vermin','vernix',
'victor','vinery','vintry','virent','virtue',
'voicer','vomity','vortex','voyeur','wicopy',
'wincer','wincey','winery','winter','wintry',
'witney','wivern','woubit','wyvern','xenium',
'ybrent','yumpie','zircon','zoetic','zombie',
'zonure','zymite','bemix','bento','benty',
'beton','bevor','bicep','biner','biome',
'biont','biter','bitou','boite','bonce',
'boner','boney','bonie','bonze','boric',
'borne','borty','bortz','bourn','bower',
'bowet','bowie','bowne','boxen','boxer',
'boxty','brent','brine','briny','brize',
'brome','bronc','brown','bruin','bruit',
'brume','brunt','brute','bumpy','bunce',
'bunco','bunty','buret','burin','burnt',
'buteo','buxom','buyer','buyin','cento',
'centu','certy','cimex','citer','civet',
'combe','combi','comby','comer','comet',
'comix','compt','comte','coney','conte',
'copen','coper','coqui','corbe','corby',
'corey','corni','cornu','corny','count',
'coupe','courb','coure','court','coven',
'cover','covet','covey','covin','cower',
'cowry','coxib','coyer','coypu','cozen',
'cozey','cozie','crept','crepy','cribo',
'crime','crimp','crine','cripe','cromb',
'crome','crone','crony','croup','crout',
'crown','croze','cruet','crumb','crump',
'cruve','crypt','cuber','cubit','cumin',
'cunei','cunit','cupro','curet','curie',
'curio','curny','curve','curvy','cuter',
'cutey','cutie','cutin','cyber','cyton',
'ebony','embow','embox','empty','enorm',
'entry','envoi','envoy','enzym','epoxy',
'equip','eruct','erupt','evict','exurb',
'imbue','impot','impro','inbox','inbye',
'incur','incut','inept','inerm','inert',
'inorb','input','inter','intro','inure',
'inver','irone','irony','ivory','meint',
'meiny','mento','mercy','merit','metic',
'metro','meynt','micro','mieux','mince',
'mincy','miner','minor','minty','minxy',
'mirex','miter','mitre','mixen','mixer',
'mixte','mixup','mizen','mobey','mobie',
'moire','moner','money','monic','monie',
'monte','monty','moper','mopey','morne',
'moten','motey','mount','mourn','mover',
'movie','mower','moxie','mpret','mucin',
'mucor','mucro','murex','murti','muter',
'muton','myope','nempt','nepit','nertz'
'nervy','netop','nicer','niter','nitre',
'nitro','nitry','nixer','noire','nomic',
'noter','notum','novum','nowty','omber',
'ombre','oncer','oncet','onery','onium',
'ontic','opine','opium','opter','optic',
'orbit','orcin','orpin','oubit','ounce',
'ourie','outby','outer','outie','outre',
'overt','ovine','owner','owrie','oxime',
'oxter','peony','pervo','pervy','petri',
'pewit','picot','piert','piety','piezo',
'piner','piney','pinot','pinto','piony',
'pioye','pique','piton','pivot','point',
'pombe','ponce','poncy','poney','ponty',
'ponzu','porin','porny','porty','potin',
'pouty','power','powin','powny','powre',
'poynt','premy','prent','preon','prexy',
'price','pricy','prime','primo','primy',
'print','prion','privy','prize','probe',
'proby','proem','proin','prone','prove',
'proxy','proyn','prune','prunt','pubco',
'pubic','pucer','pumie','punce','punim',
'punto','punty','purin','purty','puter',
'putin','puton','pyrex','pyric','pyxie',
'qubit','quern','query','queyn','quiet',
'quine','quino','quint','quipo','quire',
'quirt','quite','quoin','quoit','quote',
'quyte','rebit','rebop','rebut','rebuy',
'recit','recon','recti','recto','recut',
'remit','remix','repin','repot','retox',
'rewin','rewon','ricey','ripen','ritzy',
'riven','rivet','robin','ronte','ropey',
'roque','rouen','roupy','route','roven',
'rowen','rowie','rowme','royne','rozet',
'rozit','rubin','rumbo','rumen','rumpo',
'rumpy','runic','runty','rutin','tecum',
'tempi','tempo','tenor','tepoy','timbo',
'timer','timon','toner','toney','tonic',
'toper','topic','toque','toric','touze',
'touzy','tower','towie','towny','towze',
'towzy','toxic','toxin','toyer','tozie',
'tribe','trice','trine','tripe','tripy',
'tromp','tronc','trone','trope','trove',
'truce','trump','tuber','tumor','tumpy',
'tuner','tunic','turbo','turme','tuyer',
'twerp','twice','twier','twine','twiny',
'twire','twirp','twoer','twyer','typic',
'umber','umbre','umpie','umpty','unbox',
'uncoy','unite','unity','unmet','unmew',
'unmix','unrip','untie','unwet','unwit',
'unzip','upbow','upbye','upter','uptie',
'urbex','ureic','urent','urine','urite',
'uteri','utero','veiny','venom','venti',
'vertu','vezir','vibex','vibey','vieux',
'viewy','vimen','viner','vinew','viper',
'vireo','virtu','vitex','vitro','vixen',
'vizor','voice','vomer','vomit','voter',
'vower','vrouw','wimpy','wince','winey',
'winze','wiper','wiver','wizen','womby',
'women','womyn','wormy','woven','woxen',
'write','wrote','xenic','xeric','ybore',
'yince','yonic','yourn','yourt','youve',
'yowie','yrent','yupon','zibet','zinco',
'zincy','zineb','zombi','zoner','zowie',
'zymic','bein','beni','bent','berm',
'bevy','bice','bien','bier','bine',
'bint','biro','bite','bito','bize',
'boep','boer','boet','bone','bony',
'bore','borm','born','bort','bote',
'boun','bout','bowr','boxy','brei',
'bren','brew','brey','brie','brim',
'brin','brio','brit','brow','brut',
'bruv','brux','buco','bump','bunt',
'buoy','burn','burp','bury','bute',
'byre','byte','cent','cero','cert',
'cine','cinq','cion','cire','cite',
'cito','city','cive','coin','coir',
'coit','comb','come','comp','cone',
'coni','cony','cope','copy','core',
'corm','corn','cory','cote','coup',
'cour','cove','cowp','cowy','coxy',
'coze','cozy','crem','crew','crib',
'crim','crip','crit','cron','crop',
'crow','crue','crux','cube','cuit',
'cure','cure','curn','curt','cute',
'cyme','cyte','ebon','ecru','emic',
'emir','emit','empt','enow','envy',
'epic','eric','eruv','etic','etui',
'euoi','euro','exit','exon','expo',
'eyot','ibex','icer','icon','inby',
'inro','into','iron','item','iter',
'iure','mein','meno','ment','menu',
'meou','meow','merc','meri','mice',
'mico','mien','mine','mino','mint',
'minx','miny','mire','miro','mirv',
'miry','mite','mity','mixt','mixy',
'mobe','moby','moer','moit','mony',
'mope','mopy','more','morn','mort',
'mote','moti','motu','moue','moup',
'move','mown','moze','muir','muni',
'munt','muon','mure','mute','muti',
'myxo','nemo','neum','nevi','newb',
'newt','next','nice','nimb','nite',
'nixe','nixy','noir','nome','nope',
'nori','norm','note','noup','nout',
'nowt','nowy','numb','obey','obit',
'oint','ombu','omen','omer','omit',
'once','oner','onie','onyx','open',
'orby','oryx','otic','ourn','oven',
'over','ovum','ower','owie','owre',
'oxen','oxer','oxic','oxim','oyer',
'oyez','pein','peni','pent','peon',
'perc','peri','perm','pern','pert',
'perv','peut','pice','pier','piet',
'pine','pint','piny','pion','pioy',
'pirn','pity','pium','pixy','pize',
'poem','poet','pome','pone','pont',
'pony','pore','port','pory','pote',
'poui','pour','pout','pown','poxy',
'prem','prex','prey','prez','prim',
'prix','prob','prom','prow','ptui',
'pube','puce','puer','puir','pumy',
'punt','puny','pure','puri','putz',
'pyet','pyic','pyin','pyne','pyot',
'pyre','pyro','quem','quep','quey',
'quim','quin','quip','quit','quiz',
'quop','rein','reno','rent','reny',
'repo','rice','ricy','riem','rime',
'rimu','rimy','rine','riot','ripe',
'ript','rite','ritz','rive','rivo',
'robe','roin','romp','rone','ront',
'ronz','rope','ropy','rote','roti',
'roue','roum','roup','rout','roux',
'rove','rowt','rube','ruby','ruin',
'rume','rump','rune','runt','ryot',
'rype','tein','temp','term','tern',
'tice','tier','time','tine','tiny',
'tire','tiro','tivy','tiyn','toby',
'toey','tomb','tome','tone','tony',
'tope','topi','torc','tore','tori',
'torn','tory','toun','tour','town',
'towy','toze','trem','trew','trey',
'trez','trie','trim','trin','trio',
'trip','tron','trop','trou','trow',
'troy','true','trye','tryp','tube',
'tump','tune','tuny','turm','turn',
'twin','tyer','tyin','tymp','tyne',
'type','typo','tyre','tyro','umbo',
'umpy','unbe','unce','unci','unco',
'unit','unto','upby','upon','urbe',
'uric','vein','vent','verb','vert',
'very','veto','vext','vibe','vice',
'vier','view','vine','vino','vint',
'viny','vire','vite','vizy','voce',
'voip','voir','voix','vote','vrot',
'vrou','vrow','weir','wemb','went',
'wept','wero','wert','wice','wimp',
'wine','wino','winy','wipe','wire',
'wiry','wite','wive','womb','wont',
'wore','worm','worn','wort','wove',
'wren','writ','wrot','wyte','ybet',
'yebo','yeow','yeti','yeux','yipe',
'yite','ympe','ympt','yomp','yoni',
'yont','yore','yorp','your','yowe',
'yump','yunx','yurt','yutz','zebu',
'zein','zero','zimb','zinc','zine',
'zite','zobu','zoic','zone','zori',
'zyme','ben','bet','bey	bez',
'bin','bio','bit','biz','boi',
'bon','bop','bor','bot','bow',
'box','boy','bro','bru','bum',
'bun','bur','but','buy','bye',
'cep','cit','cob','con','cop',
'coq','cor','cot','cow','cox',
'coy','coz','cru','cry','cub',
'cue','cup','cur','cut','cuz',
'cwm','eco','ecu','emo','emu',
'eon','erm','ern','evo','ewt',
'exo','ice','icy','imp','imu',
'ion','ire','ivy','men','met',
'meu','mew','mib','mic','mir',
'mix','miz','mob','moc','moe',
'moi','mon','mop','mor','mot',
'mou','mow','moy','moz','mun',
'mut','mux','myc','neb','nep',
'net','new','nib','nie','nim',
'nip','nit','nix','nob','nom',
'nor','not','now','nox','noy',
'nub','nur','nut','nye','nym',
'obe','obi','obv','oer','one',
'ony','ope','opt','orb','orc',
'ore','ort','oup','our','out',
'owe','own','owt','oxy','oye',
'pec','pen','per','pet','pew',
'pic','pie','pin','pir','pit',
'piu','pix','poi','pom','pot',
'pow','pox','poz','pre','pro',
'pry','pub','pun','pur','put',
'puy','pwn','pye','pyx','qin',
'que','qui','quo','reb','rec',
'rei','rem','ren','reo','rep',
'ret','rev','rew','rex','rez',
'rib','rim','rin','rip','rit',
'riz','rob','roc','roe','rom',
'rot','row','rub','ruc','rue',
'rum','run','rut','rye','ryu',
'tec','ten','tew','tex','tic',
'tie','tin','tip','tix','tiz',
'toc','toe','tom','ton','top',
'tor','tow','toy','try','tub',
'tui','tum','tun','tup','tur',
'tux','two','twp','tye','uey',
'ume','ump','uni','upo','urb',
'ure','urn','urp','ute','vet',
'vex','vie','vim','vin','vip',
'voe','vom','von','vor','vow',
'vox','vum','web','wem','wen',
'wet','wex','wey','win','wit',
'wiz','woe','won','wop','wot',
'wox','wry','wuz','wye','wyn',
'yen','yep','yer','yet','yew',
'yex','yez','yin','yip','yiz',
'yob','yom','yon','you','yow',
'yum','yup','zen','zep','zex',
'zin','zip','zit','be','bi',
'bo','by','em','en','er',
'et','ew','ex','in','io',
'it','me','mi','mo','mu',
'my','ne','no','nu','ny',
'ob','oe','oi','om','on',
'op','or','ou','ow','ox',
'oy','pe','pi','po','qi',
're','te','ti','to','um',
'un','up','ur','ut','vu',
'we','wo','xi','xu','ye',
'yo','yu','ze','zo']

top_home_row = ['farsightedly', 'fluoridates', 'playwrights', 'profligates', 'quatrefoils', 'righteously', 'southwardly', 'afterglows', 'daughterly', 'dayflowers', 'depilatory', 'depositary', 'dialoguers', 'dipetalous', 'droplights', 'dwarfishly', 'epistolary', 'farsighted', 'fieldworks', 'flourished', 'fluoridate', 'flyweights', 'freakishly', 'glyphosate', 'hyperdulia', 'ideographs', 'ideography', 'lifeguards', 'outlawries', 'playwright', 'preholiday', 'prequalify', 'profligate', 'quatrefoil', 'shadowlike', 'shoplifted', 'shoplifter', 'spheroidal', 'sprightful', 'superlight', 'thylakoids', 'tradesfolk', 'upholstery', 'uplighters', 'worshipful', 'aeroliths', 'afterglow', 'atrophied', 'atrophies', 'autopsied', 'autoreply', 'daughters', 'dayflower', 'daylights', 'deflators', 'desultory', 'dialoguer', 'dialogues', 'dipterous', 'dishtowel', 'dishwater', 'displayer', 'doughiest', 'doughtier', 'doughtily', 'drawliest', 'droplight', 'dwarflike', 'eightfold', 'epidurals', 'epilators', 'estradiol', 'eupatrids', 'feudalist', 'feudality', 'feudatory', 'fieldwork', 'filatures', 'fireplugs', 'fishplate', 'flatworks', 'fleaworts', 'floriated', 'flouriest', 'fluorides', 'fluorites', 'flyweight', 'foliature', 'foreplays', 'foresight', 'forsythia', 'frostlike', 'frugality', 'fruitages', 'gasholder', 'gatefolds', 'gearshift', 'ghastlier', 'ghostlier', 'ghostlike', 'giftwraps', 'giltheads', 'goatherds', 'goatishly', 'grapeshot', 'guidepost', 'hairstyle', 'hayfields', 'headfirst', 'heliports', 'hideously', 'holytides', 'horseplay', 'horsetail', 'hydrogels', 'hydrolase', 'ideograph', 'idolaters', 'isotheral', 'jailhouse', 'judgeship', 'leapfrogs', 'leftwards', 'lifeguard', 'lifeworks', 'ligatured', 'ligatures', 'odalisque', 'outfields', 'outplayed', 'outraised', 'outspread', 'outwardly', 'outweighs', 'pileworts', 'pilotages', 'piteously', 'playgoers', 'playhouse', 'plowshare', 'poultries', 'praiseful', 'preflight', 'prodigals', 'profusely', 'prudishly', 'quartiles', 'redisplay', 'requitals', 'rhyolites', 'ridgeways', 'righteous', 'roguishly', 'ropewalks', 'royalties', 'safelight', 'seaworthy', 'shiftwork', 'slaughter', 'southerly', 'epilator', 'equality', 'equators', 'esophagi', 'eulogist', 'eupatrid', 'euphoria', 'euphrasy', 'fadeouts', 'failures', 'fatherly', 'fatigued', 'fatigues', 'faultier', 'feldspar', 'fighters', 'figurate', 'figworts', 'filature', 'firedogs', 'fireplug', 'firepots', 'fistulae', 'flagship', 'flakiest', 'flashier', 'flatwise', 'flatwork', 'fleapits', 'fleawort', 'fleshpot', 'floaters', 'flourish', 'flouter', 'flowages', 'flukiest', 'fluoride', 'fluorite', 'flytraps', 'fogeyish', 'foliaged', 'foliated', 'foliates', 'folksier', 'folkways', 'foreguts', 'forelady', 'forepaws', 'foreplay', 'foresaid', 'foresail', 'forestay', 'forkedl', 'fortyish', 'foulards', 'fourthly', 'frailest', 'freakily', 'freakish', 'freights', 'frigates', 'frijoles', 'froglike', 'frostily', 'frothily', 'fruitage', 'fudgiest', 'gadflies', 'galipots', 'garishly', 'garpikes', 'gasolier', 'gatefold', 'gaudiest', 'gawkiest', 'gestural', 'giftedly', 'giftware', 'giftwrap', 'gilthead', 'ligature', 'lighters', 'liquated', 'liquates', 'liquored', 'litharge', 'loathers', 'lodestar', 'lordship', 'lutefisk', 'oafishly', 'oldsquaw', 'opaquely', 'outdraws', 'outfield', 'outflies', 'outlawed', 'outlawry', 'outleaps', 'outliers', 'outplays', 'outraged', 'outrages', 'outraise', 'outrides', 'outsider', 'outwards', 'outwears', 'outweigh', 'palfreys', 'parkiest', 'parodies', 'parodist', 'parotids', 'parquets', 'pastored', 'pastured', 'peafowls', 'pergolas', 'perilous', 'philters', 'physique', 'pilaster', 'pilewort', 'pilotage', 'pirogues', 'pistoled', 'pitheads', 'plaudits', 'playgoer', 'playsuit', 'plethora', 'pleurisy', 'plighted', 'ploughed', 'plushier', 'podgiest', 'podiatry', 'polarity', 'polestar', 'polished', 'polisher', 'polyuria', 'porkiest', 'portaged', 'portages', 'portside', 'postgrad', 'postlude', 'postural', 'postured', 'potheads', 'potshard', 'potsherd', 'powerful', 'prefight', 'preloads', 'prideful', 'priestly', 'prodigal', 'profiled', 'profiles', 'profited', 'proudest', 'psaltery', 'pudgiest', 'pulsated', 'putridly', 'quartile', 'quayside', 'queasily', 'quilters', 'quipster', 'rakishly', 'rapidest', 'rawhides', 'readjust', 'readopts', 'readouts', 'redshift', 'refights', 'refloats', 'refought', 'regality', 'regolith', 'relights', 'requital', 'residual', 'rhapsody', 'rhyolite', 'ridgeway', 'rightful', 'riposted', 'ropewalk', 'ropeway', 'roughest', 'roulades', 'rowdiest', 'royalist', 'seatwork', 'sedulity', 'seraglio', 'shakeout', 'shipload', 'shipyard', 'shitload', 'shoplift', 'shoptalk', 'shortage', 'shoulder', 'showgirl', 'shrewdly', 'sidewalk', 'skylight', 'skywrite', 'skywrote', 'slighted', 'slighter', 'slipware', 'slithery', 'sloughed', 'sodality', 'softhead', 'software', 'soldiery', 'solidary', 'solitary', 'solitude', 'southpaw', 'sparkled', 'spheroid', 'spiraled', 'spiteful', 'splurged', 'spoilage', 'sportily', 'sprawled', 'spritely', 'sprouted', 'squarely', 'aphides', 'apishly', 'apostil', 'apostle', 'aquifer', 'argyles', 'aroused', 'aspired', 'astride', 'atrophy', 'audiles', 'auditor', 'auklets', 'authors', 'autopsy', 'darkest', 'darkies', 'darkish', 'darkles', 'dashier', 'dashpot', 'dasyure', 'daygirl', 'deathly', 'default', 'defrags', 'defrays', 'defrost', 'delight', 'departs', 'deploys', 'deports', 'deposal', 'deposit', 'derails', 'desktop', 'despair', 'despoil', 'destroy', 'details', 'detours', 'dewlaps', 'dialers', 'dialogs', 'diapers', 'dietary', 'diethyl', 'diglots', 'digraph', 'dilates', 'dilator', 'diluter', 'dilutes', 'dilutor', 'diopter', 'diphase', 'diploes', 'dipolar', 'dipoles', 'direful', 'dishful', 'dishrag', 'display', 'disport', 'dispute', 'disrupt', 'dithers', 'dithery', 'dogfish', 'doglike', 'doltish', 'dopiest', 'dotages', 'doughty', 'dourest', 'dowager', 'dowries', 'doylies', 'draught', 'drogues', 'fogyish', 'foisted', 'folders', 'foliage', 'foliate', 'folkies', 'folkway', 'foraged', 'forages', 'forayed', 'foregut', 'forepaw', 'foresaw', 'forgets', 'forsake', 'forties', 'foulard', 'foulest', 'fourths', 'fowlers', 'fragile', 'frailty', 'fraught', 'freight', 'freshly', 'fretsaw', 'fridges', 'frigate', 'frights', 'frijole', 'frisked', 'frosted', 'frothed', 'fruited', 'fudgier', 'fustier', 'fustily', 'gaiters', 'galipot', 'garfish', 'garpike', 'gathers', 'gaudery', 'gaudier', 'gaudies', 'gaudily', 'gawkers', 'gawkier', 'gawkily', 'gelatos', 'ghastly', 'ghosted', 'ghostly', 'gilders', 'girasol', 'girdles', 'girthed', 'gliders', 'glister', 'gloated', 'gloater', 'gloried', 'glories', 'glorify', 'glowers', 'gluepot', 'gluiest', 'goalies', 'goatish', 'godlier', 'godlike', 'godwits', 'goiters', 'golfers', 'goliard', 'goliath', 'gophers', 'goriest', 'goshawk', 'goulash', 'hokiest', 'holders', 'holdups', 'holiday', 'holiest', 'holster', 'hopeful', 'hoplite', 'hosiery', 'hostage', 'hostile', 'hostler', 'hotspur', 'howlers', 'hurdles', 'hurlies', 'hurtled', 'hurtles', 'huskier', 'huskily', 'hustled', 'hustler', 'hyalite', 'hydrate', 'hydrous', 'hypogea', 'iodates', 'irately', 'isohyet', 'isolate', 'jailers', 'jailors', 'jarfuls', 'jealous', 'jerkily', 'jetfoil', 'jewfish', 'jilters', 'jodhpur', 'joisted', 'jolters', 'joltier', 'jostled', 'jostler', 'joukery', 'jousted', 'jouster', 'jowaris', 'jowlers', 'jowlier', 'joypads', 'joyride', 'judgers', 'judgier', 'judogis', 'judoist', 'judokas', 'jughead', 'juglets', 'juliets', 'jupatis', 'justify', 'ustled', 'kagoule', 'kagouls', 'kajeput', 'kaliphs', 'karites', 'karoshi', 'kashrut', 'kathode', 'katipos', 'kauries', 'kaylied', 'keitloa', 'keloids', 'loathes', 'lodgers', 'lofters', 'loftier', 'logiest', 'logways', 'loiters', 'loquats', 'loudest', 'loudish', 'louries', 'lousier', 'loutery', 'loutish', 'lowries', 'ludship', 'lurgies', 'lushier', 'lustier', 'lustred', 'lutfisk', 'luthier', 'lyrated', 'oakiest', 'oarfish', 'oariest', 'oarlike', 'oatlike', 'odalisk', 'oedipal', 'oestral', 'ogreish', 'oilways', 'oldster', 'oldwife', 'olestra', 'opaqued', 'opaquer', 'opaques', 'ophites', 'ophiura', 'opiated', 'opiatesralist', 'orality', 'ordeals', 'orgeats', 'orgiast', 'ostiary', 'otaries', 'oughted', 'ougiyas', 'ouglied', 'ouglies', 'ouldest', 'ouralis', 'ouriest', 'ourself', 'outages', 'outdare', 'outdrag', 'outdraw', 'outdrew', 'outfire', 'outfish', 'outflew', 'outgrew', 'outhear', 'outhire', 'outhyre', 'outlaid', 'outlash', 'outlaws', 'outlays', 'outlead', 'outleap', 'outlers', 'outlied', 'outlier', 'outlies', 'kephirs', 'keypads', 'keypals', 'keyword', 'sh', 'si', 'so', 'st', 'ta', 'te', 'ti', 'to', 'ug', 'uh', 'up', 'ur', 'us', 'ut', 'we', 'wo', 'ya', 'ye', 'yi', 'yo', 'toe', 'tog', 'top', 'tor', 'tow', 'toy', 'try', 'tsk', 'tug', 'tui', 'tup', 'twa', 'two', 'twp', 'tye', 'tyg', 'udo', 'uds', 'uey', 'ufo', 'ugh', 'ugs', 'uke', 'ule', 'upo', 'ups', 'urd', 'ure', 'urp', 'use', 'uta', 'ute', 'uts', 'wad', 'wae', 'wag', 'wai', 'wap', 'war', 'was', 'wat', 'way', 'wed', 'wet', 'wey', 'wha', 'who', 'why', 'wig', 'wis', 'wit', 'woe', 'wof', 'wog', 'wok', 'wop', 'wos', 'wot', 'wry', 'wud', 'wus', 'wye', 'yad', 'yae', 'yag', 'yah', 'yak', 'yap', 'yar', 'yas', 'yaw', 'yea', 'yeh', 'yep', 'yer', 'yes', 'yet', 'yew', 'ygo', 'yid', 'pir', 'pis', 'pit', 'piu', 'plu', 'ply', 'poa', 'pod', 'poh', 'poi', 'pol', 'pos', 'pot', 'pow', 'pre', 'pro', 'pry', 'psi', 'pst', 'pud', 'pug', 'puh', 'pul', 'pur', 'pus', 'put', 'puy', 'pya', 'pye', 'qat', 'qis', 'qua', 'rad', 'rag', 'rah', 'rai', 'raj', 'rap', 'ras', 'rat', 'raw', 'ray', 'red', 'ref', 'reg', 'reh', 'rei', 'reo', 'rep', 'res', 'ret', 'rew', 'rho', 'rhy', 'ria', 'rid', 'rif', 'rig', 'rip', 'rit', 'rod', 'roe', 'rok', 'rot', 'row', 'rud', 'rue', 'rug', 'rut', 'rya', 'rye', 'ryu', 'sad', 'sae', 'sag', 'sai', 'sal', 'sap', 'sar', 'sat', 'wost', 'wots', 'wrap', 'writ', 'wuds', 'wyes', 'wyle', 'wyte', 'yads', 'yage', 'yagi', 'yags', 'yahs', 'yaks', 'yald', 'yale', 'yaps', 'yard', 'yare', 'yark', 'yate', 'yaud', 'yaup', 'yawl', 'yawp', 'yawe', 'yead', 'yeah', 'year', 'yeas', 'yeld', 'yelk', 'yelp', 'yelt', 'yeow', 'yeps', 'yerd', 'yerk', 'yesk', 'yest', 'yeti', 'yeuk', 'yews', 'ygoe', 'yids', 'yike', 'yipe', 'yips', 'yird', 'yirk', 'yite', 'ylke', 'yode', 'yodh', 'yods', 'yoga', 'yogh', 'yogi', 'yoke', 'yoks', 'yold', 'yolk', 'yore', 'york', 'yorp', 'youk', 'your', 'yous', 'yowe', 'yowl', 'yows', 'yuft', 'yuga', 'yugs', 'yuke', 'yuko', 'yuks', 'yule', 'yups', 'yurt', 'wart', 'wary', 'wase', 'wash', 'wasp', 'wast', 'wate', 'wats', 'wauk', 'waul', 'waur', 'ways', 'weak', 'weal', 'wear', 'weds', 'weft', 'weid', 'weil', 'weir', 'weka', 'weld', 'welk', 'wels', 'welt', 'wept', 'wero', 'wert', 'west', 'weta', 'wets', 'weys', 'whae', 'whap', 'what', 'whet', 'whey', 'whid', 'whig', 'whio', 'whip', 'whir', 'whit', 'whoa', 'whop', 'whot', 'whup', 'whys', 'wide', 'wiel', 'wife', 'wigs', 'wild', 'wile', 'wilt', 'wily', 'wipe', 'wir', 'wiry', 'wise', 'wish', 'wisp', 'wist', 'wite', 'with', 'wits', 'woad', 'woah', 'woes', 'wofs', 'wogs', 'woke', 'woks', 'wold', 'wolf', 'wops', 'tuis', 'tule', 'tups', 'turd', 'turf', 'turk', 'tush', 'tusk', 'twae', 'twal', 'twas', 'tway', 'twig', 'twos', 'tyde', 'tyed', 'tyer', 'tyes', 'tygs', 'tyke', 'type', 'typo', 'tyre', 'tyro', 'udal', 'udos', 'ueys', 'ufos', 'ughs', 'ugly', 'ukes', 'ules', 'upas', 'updo', 'upgo', 'upsy', 'upta', 'urao', 'urde', 'urds', 'urdy', 'urea', 'ures', 'urge', 'urps', 'ursa', 'used', 'user', 'utas', 'utes', 'utis', 'wade', 'wadi', 'wads', 'wadt', 'wady', 'waes', 'waft', 'wage', 'wags', 'waid', 'waif', 'wail', 'wair', 'wais', 'wait', 'wake', 'wakf', 'wald', 'wale', 'wali', 'walk', 'waly', 'waps', 'waqf', 'ward', 'ware', 'wark', 'warp', 'wars']

eng_words = ['the', 'of', 'to', 'and', 'a', 'in', 'is', 'it', 'you', 'that', 'he', 'was', 'for', 'on', 'are', 'with', 'as', 'I', 'his', 'they', 'be', 'at', 'one', 'have', 'this', 'from', 'or', 'had', 'by', 'not', 'word', 'but', 'what', 'some', 'we', 'can', 'out', 'other', 'were', 'all', 'there', 'when', 'up', 'use', 'your', 'how', 'said', 'an', 'each', 'she', 'which', 'do', 'their', 'time', 'if', 'will', 'way', 'about', 'many', 'then', 'them', 'write', 'would', 'like', 'so', 'these', 'her', 'long', 'make', 'thing', 'see', 'him', 'two', 'has', 'look', 'more', 'day', 'could', 'go', 'come', 'did', 'number', 'sound', 'no', 'most', 'people', 'my', 'over', 'know', 'water', 'than', 'call', 'first', 'who', 'may', 'down', 'side', 'been', 'now', 'find', 'any', 'new', 'work', 'part', 'take', 'get', 'place', 'made', 'live', 'where', 'after', 'back', 'little', 'only', 'round', 'man', 'year', 'came', 'show', 'every', 'good', 'me', 'give', 'our', 'under', 'name', 'very', 'through', 'just', 'form', 'sentence', 'great', 'think', 'say', 'help', 'low', 'line', 'differ', 'turn', 'cause', 'much', 'mean', 'before', 'move', 'right', 'boy', 'old', 'too', 'same', 'tell', 'does', 'set', 'three', 'want', 'air', 'well', 'also', 'play', 'small', 'end', 'put', 'home', 'read', 'hand', 'port', 'large', 'spell', 'add', 'even', 'land', 'here', 'must', 'big', 'high', 'such', 'follow', 'act', 'why', 'ask', 'men', 'change', 'went', 'light', 'kind', 'off', 'need', 'house', 'picture', 'try', 'us', 'again', 'animal', 'point', 'mother', 'world', 'near', 'build', 'self', 'earth', 'father', 'head', 'stand', 'own', 'page', 'should', 'country', 'found', 'answer', 'school', 'grow', 'study', 'still', 'learn', 'plant', 'cover', 'food', 'sun', 'four', 'between', 'state', 'keep', 'eye', 'never', 'last', 'let', 'thought', 'city', 'tree', 'cross', 'farm', 'hard', 'start', 'might', 'story', 'saw', 'far', 'sea', 'draw', 'left', 'late', 'run', "don't", 'while', 'press', 'close', 'night', 'real', 'life', 'few', 'north', 'open', 'seem', 'together', 'next', 'white', 'children', 'begin', 'got', 'walk', 'example', 'ease', 'paper', 'group', 'always', 'music', 'those', 'both', 'mark', 'often', 'letter', 'until', 'mile', 'river', 'car', 'feet', 'care', 'second', 'book', 'carry', 'took', 'science', 'eat', 'room', 'friend', 'began', 'idea', 'fish', 'mountain', 'stop', 'once', 'base', 'hear', 'horse', 'cut', 'sure', 'watch', 'color', 'face', 'wood', 'main', 'enough', 'plain', 'girl', 'usual', 'young', 'ready', 'above', 'ever', 'red', 'list', 'though', 'feel', 'talk', 'bird', 'soon', 'body', 'dog', 'family', 'direct', 'pose', 'leave', 'song', 'measure', 'door', 'product', 'black', 'short', 'numeral', 'class', 'wind', 'question', 'happen', 'complete', 'ship', 'area', 'half', 'rock', 'order', 'fire', 'south', 'problem', 'piece', 'told', 'knew', 'pass', 'since', 'top', 'whole', 'king', 'space', 'heard', 'best', 'hour', 'better', 'true', 'during', 'hundred', 'five', 'remember', 'step', 'early', 'hold', 'west', 'ground', 'interest', 'reach', 'fast', 'verb', 'sing', 'listen', 'six', 'table', 'travel', 'less', 'morning', 'ten', 'simple', 'several', 'vowel', 'toward', 'war', 'lay', 'against', 'pattern', 'slow', 'center', 'love', 'person', 'money', 'serve', 'appear', 'road', 'map', 'rain', 'rule', 'govern', 'pull', 'cold', 'notice', 'voice', 'unit', 'power', 'town', 'fine', 'certain', 'fly', 'fall', 'lead', 'cry', 'dark', 'machine', 'note', 'wait', 'plan', 'figure', 'star', 'box', 'noun', 'field', 'rest', 'correct', 'able', 'pound', 'done', 'beauty', 'drive', 'stood', 'contain', 'front', 'teach', 'week', 'final', 'gave', 'green', 'oh', 'quick', 'develop', 'ocean', 'warm', 'free', 'minute', 'strong', 'special', 'mind', 'behind', 'clear', 'tail', 'produce', 'fact', 'street', 'inch', 'multiply', 'nothing', 'course', 'stay', 'wheel', 'full', 'force', 'blue', 'object', 'decide', 'surface', 'deep', 'moon', 'island', 'foot', 'system', 'busy', 'test', 'record', 'boat', 'common', 'gold', 'possible', 'plane', 'stead', 'dry', 'wonder', 'laugh', 'thousand', 'ago', 'ran', 'check', 'game', 'shape', 'equate', 'hot', 'miss', 'brought', 'heat', 'snow', 'tire', 'bring', 'yes', 'distant', 'fill', 'east', 'paint', 'language', 'among', 'grand', 'ball', 'yet', 'wave', 'drop', 'heart', 'am', 'present', 'heavy', 'dance', 'engine', 'position', 'arm', 'wide', 'sail', 'material', 'size', 'vary', 'settle', 'speak', 'weight', 'general', 'ice', 'matter', 'circle', 'pair', 'include', 'divide', 'syllable', 'felt', 'perhaps', 'pick', 'sudden', 'count', 'square', 'reason', 'length', 'represent', 'art', 'subject', 'region', 'energy', 'hunt', 'probable', 'bed', 'brother', 'egg', 'ride', 'cell', 'believe', 'fraction', 'forest', 'sit', 'race', 'window', 'store', 'summer', 'train', 'sleep', 'prove', 'lone', 'leg', 'exercise', 'wall', 'catch', 'mount', 'wish', 'sky', 'board', 'joy', 'winter', 'sat', 'written', 'wild', 'instrument', 'kept', 'glass', 'grass', 'cow', 'job', 'edge', 'sign', 'visit', 'past', 'soft', 'fun', 'bright', 'gas', 'weather', 'month', 'million', 'bear', 'finish', 'happy', 'hope', 'flower', 'clothe', 'strange', 'gone', 'jump', 'baby', 'eight', 'village', 'meet', 'root', 'buy', 'raise', 'solve', 'metal', 'whether', 'push', 'seven', 'paragraph', 'third', 'shall', 'held', 'hair', 'describe', 'cook', 'floor', 'either', 'result', 'burn', 'hill', 'safe', 'cat', 'century', 'consider', 'type', 'law', 'bit', 'coast', 'copy', 'phrase', 'silent', 'tall', 'sand', 'soil', 'roll', 'temperature', 'finger', 'industry', 'value', 'fight', 'lie', 'beat', 'excite', 'natural', 'view', 'sense', 'ear', 'else', 'quite', 'broke', 'case', 'middle', 'kill', 'son', 'lake', 'moment', 'scale', 'loud', 'spring', 'observe', 'child', 'straight', 'consonant', 'nation', 'dictionary', 'milk', 'speed', 'method', 'organ', 'pay', 'age', 'section', 'dress', 'cloud', 'surprise', 'quiet', 'stone', 'tiny', 'climb', 'cool', 'design', 'poor', 'lot', 'experiment', 'bottom', 'key', 'iron', 'single', 'stick', 'flat', 'twenty', 'skin', 'smile', 'crease', 'hole', 'trade', 'melody', 'trip', 'office', 'receive', 'row', 'mouth', 'exact', 'symbol', 'die', 'least', 'trouble', 'shout', 'except', 'wrote', 'seed', 'tone', 'join', 'suggest', 'clean', 'break', 'lady', 'yard', 'rise', 'bad', 'blow', 'oil', 'blood', 'touch', 'grew', 'cent', 'mix', 'team', 'wire', 'cost', 'lost', 'brown', 'wear', 'garden', 'equal', 'sent', 'choose', 'fell', 'fit', 'flow', 'fair', 'bank', 'collect', 'save', 'control', 'decimal', 'gentle', 'woman', 'captain', 'practice', 'separate', 'difficult', 'doctor', 'please', 'protect', 'noon', 'whose', 'locate', 'ring', 'character', 'insect', 'caught', 'period', 'indicate', 'radio', 'spoke', 'atom', 'human', 'history', 'effect', 'electric', 'expect', 'crop', 'modern', 'element', 'hit', 'student', 'corner', 'party', 'supply', 'bone', 'rail', 'imagine', 'provide', 'agree', 'thus', 'capital', "won't", 'chair', 'danger', 'fruit', 'rich', 'thick', 'soldier', 'process', 'operate', 'guess', 'necessary', 'sharp', 'wing', 'create', 'neighbor', 'wash', 'bat', 'rather', 'crowd', 'corn', 'compare', 'poem', 'string', 'bell', 'depend', 'meat', 'rub', 'tube', 'famous', 'dollar', 'stream', 'fear', 'sight', 'thin', 'triangle', 'planet', 'hurry', 'chief', 'colony', 'clock', 'mine', 'tie', 'enter', 'major', 'fresh', 'search', 'send', 'yellow', 'gun', 'allow', 'print', 'dead', 'spot', 'desert', 'suit', 'current', 'lift', 'rose', 'continue', 'block', 'chart', 'hat', 'sell', 'success', 'company', 'subtract', 'event', 'particular', 'deal', 'swim', 'term', 'opposite', 'wife', 'shoe', 'shoulder', 'spread', 'arrange', 'camp', 'invent', 'cotton', 'born', 'determine', 'quart', 'nine', 'truck', 'noise', 'level', 'chance', 'gather', 'shop', 'stretch', 'throw', 'shine', 'property', 'column', 'molecule', 'select', 'wrong', 'gray', 'repeat', 'require', 'broad', 'prepare', 'salt', 'nose', 'plural', 'anger', 'claim', 'continent', 'oxygen', 'sugar', 'death', 'pretty', 'skill', 'women', 'season', 'solution', 'magnet', 'silver', 'thank', 'branch', 'match', 'suffix', 'especially', 'fig', 'afraid', 'huge', 'sister', 'steel', 'discuss', 'forward', 'similar', 'guide', 'experience', 'score', 'apple', 'bought', 'led', 'pitch', 'coat', 'mass', 'card', 'band', 'rope', 'slip', 'win', 'dream', 'evening', 'condition', 'feed', 'tool', 'total', 'basic', 'smell', 'valley', 'nor', 'double', 'seat', 'arrive', 'master', 'track', 'parent', 'shore', 'division', 'sheet', 'substance', 'favor', 'connect', 'post', 'spend', 'chord', 'fat', 'glad', 'original', 'share', 'station', 'dad', 'bread', 'charge', 'proper', 'bar', 'offer', 'segment', 'slave', 'duck', 'instant', 'market', 'degree', 'populate', 'chick', 'dear', 'enemy', 'reply', 'drink', 'occur', 'support', 'speech', 'nature', 'range', 'steam', 'motion', 'path', 'liquid', 'log', 'meant', 'quotient', 'teeth', 'shell', 'neck']

bottom_row = ['bacon','baize','banco','bavin','beano','beaux','bemix','biome','bonce','bonie','bonza','bonze','unmix','vacui','vacuo','venom','vibex','vieux','vimen','vinca','vixen','vocab','voema','voice','xenia','xenic','zambo','zinco','zineb','zombi','unmix','vacui','vacuo','venom','vibex','vieux','vimen','vinca','vixen','vocab','voema','voice','xenia','xenic','zambo','zinco','zineb','zombi','boxen','amoebic', 'benzoic','bivouac','acumen','aecium','aeonic','compulsative','customizable','exculpations']

# print([i.lower() for i in top_row])

generated_string=''

def randomiser(row_type, set_difficulty, set_words):
    '''This is the main function that is nested in all the other functions'''
    global generated_string
    max_length = max([len(i) for i in row_type])
    
    difficulty_decision = {'easy': 4,
                           'intermediate': int(max_length*0.75),
                           'hard': max_length}

    length_decision={'quick': [i for i in range(5, 11)],
                     'short': [i for i in range(10, 21)],
                     'medium': [i for i in range(20, 26)],
                     'hard': [i for i in range(25, 41)],
                     'hectic': [i for i in range(40, 50)]}

    possible_words = [i for i in row_type if len(i) <= difficulty_decision[set_difficulty]]
    generated_string = ' '.join(sample(possible_words, choice(length_decision[set_words])))
    #g_sring:=generated_string
    return generated_string


def randomiser_top_row(set_difficulty, set_words):
    '''This function generates a random set of words from top row'''
    return randomiser(top_row, set_difficulty, set_words)

def randomiser_home_row(set_difficulty, set_words):
    '''This function generates a random set of words from home row'''
    return randomiser(home_row, set_difficulty, set_words)

def randomiser_bottom_row(set_difficulty, set_words):
    '''This function generates a random set of words from bottom row'''
    return randomiser(bottom_row, set_difficulty, set_words)

def randomiser_top_home_row(set_difficulty, set_words):
    '''This function generates a random set of words from top and home row'''
    return randomiser(top_home_row, set_difficulty, set_words)

def randomiser_home_bottom_row(set_difficulty, set_words):
    '''This function generates a random set of words from home and bottom row'''
    return randomiser(home_bottom_row, set_difficulty, set_words)
 
def randomiser_top_bottom_row(set_difficulty, set_words):
    '''This function generates a random set of words from top and bottom row'''
    return randomiser(top_bottom_row, set_difficulty, set_words)

def randomiser_common_eng_words(set_difficulty, set_words):
    '''This function generates a random set of words from common english words'''
    return randomiser(eng_words, set_difficulty, set_words)

# def randomiser_paragraph(set_difficulty, set_words):
#     '''This function generates a random paragraph'''
#     return randomiser(paragraph, set_difficulty, set_words)